export function getInitialRecipes() {
  return [
    {
      id: 'oatmeal-bowl',
      source: 'default',
      nombre: 'Oatmeal bowl with berries and walnuts',
      descripcion: 'Complete, filling and nutritious breakfast. Rich in fiber, calcium and healthy fats.',
      ingredientes: [
        { nombre: 'Rolled oats', cantidad: 60, unidad: 'g', categoria: 'grains' },
        { nombre: 'Semi-skimmed milk', cantidad: 200, unidad: 'ml', categoria: 'dairy' },
        { nombre: 'Mixed berries (blueberries, raspberries)', cantidad: 80, unidad: 'g', categoria: 'fruits' },
        { nombre: 'Walnuts', cantidad: 20, unidad: 'g', categoria: 'other' },
        { nombre: 'Banana', cantidad: 1, unidad: 'unit', categoria: 'fruits' },
        { nombre: 'Chia seeds', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Cinnamon', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Heat the milk in a saucepan or microwave.',
        'Add the oats and cook for 3-4 minutes, stirring.',
        'Pour into a bowl and top with sliced banana, berries, walnuts and chia seeds.',
        'Sprinkle with cinnamon to taste.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['breakfast'],
      etiquetas: ['quick', 'high-fiber', 'calcium-rich', 'breastfeeding', 'filling'],
      notas: 'Can be prepared the night before as overnight oats (cold oats).',
      favorita: true,
      creadaEn: '2026-03-19',
    },
    {
      id: 'avocado-toast',
      source: 'default',
      nombre: 'Avocado toast with egg and tomato',
      descripcion: 'Quick breakfast rich in healthy fats, protein and vitamins.',
      ingredientes: [
        { nombre: 'Whole wheat bread', cantidad: 2, unidad: 'units', categoria: 'grains' },
        { nombre: 'Ripe avocado', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Egg', cantidad: 2, unidad: 'units', categoria: 'protein' },
        { nombre: 'Cherry tomatoes', cantidad: 80, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Toast the whole wheat bread.',
        'Mash the avocado with a fork and spread on the toast.',
        'Fry or scramble the eggs in a pan with a little oil.',
        'Place the eggs on the toast and add halved cherry tomatoes.',
        'Drizzle with olive oil and salt.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['breakfast'],
      etiquetas: ['quick', 'high-protein', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'butternut-squash-soup',
      source: 'default',
      nombre: 'Butternut squash and carrot soup',
      descripcion: 'Comforting, smooth and perfect for batch cooking. Rich in vitamin A and fiber.',
      ingredientes: [
        { nombre: 'Butternut squash', cantidad: 500, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Carrot', cantidad: 3, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Onion', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Potato', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Vegetable broth', cantidad: 500, unidad: 'ml', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Nutmeg', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Peel and chop the squash, carrots, onion and potato.',
        'Sauté the onion in a pot with olive oil for 3-4 minutes.',
        'Add the rest of the vegetables and cover with broth.',
        'Cook on medium heat for 20-25 minutes until tender.',
        'Blend until smooth.',
        'Season with salt and nutmeg.',
      ],
      tiempoMinutos: 35,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'high-fiber', 'breastfeeding', 'filling'],
      notas: 'Can be frozen in individual portions. Keeps 4-5 days in the fridge.',
      favorita: true,
      creadaEn: '2026-03-19',
    },
    {
      id: 'lemon-chicken',
      source: 'default',
      nombre: 'Lemon chicken with potatoes and broccoli',
      descripcion: 'Complete, nutritious and easy to make on a single sheet pan.',
      ingredientes: [
        { nombre: 'Chicken breast', cantidad: 500, unidad: 'g', categoria: 'protein' },
        { nombre: 'Potato', cantidad: 4, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Broccoli', cantidad: 300, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Lemon', cantidad: 1, unidad: 'unit', categoria: 'fruits' },
        { nombre: 'Extra virgin olive oil', cantidad: 3, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Garlic', cantidad: 2, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Dried oregano', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Preheat oven to 200°C / 400°F.',
        'Cut potatoes into wedges and place on a baking sheet with oil.',
        'Roast potatoes for 15 minutes.',
        'Meanwhile, slice chicken and marinate with lemon juice, minced garlic, oregano and oil.',
        'Add chicken and broccoli to the sheet pan.',
        'Roast for 20 more minutes until chicken is golden.',
      ],
      tiempoMinutos: 40,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['high-protein', 'calcium-rich', 'breastfeeding', 'filling'],
      notas: 'Everything on one pan = minimal effort. Leftovers reheat great the next day.',
      favorita: true,
      creadaEn: '2026-03-19',
    },
    {
      id: 'quick-lentils',
      source: 'default',
      nombre: 'Quick lentils with vegetables',
      descripcion: 'Nutritious, rich in iron and plant protein. Perfect for batch cooking.',
      ingredientes: [
        { nombre: 'Canned lentils', cantidad: 2, unidad: 'can', categoria: 'grains' },
        { nombre: 'Carrot', cantidad: 2, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Zucchini', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Crushed tomatoes', cantidad: 400, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Onion', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Garlic', cantidad: 2, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Sweet paprika', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Cumin', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Dice the onion, garlic, carrot and zucchini into small cubes.',
        'Sauté onion and garlic in a pot with oil for 3 minutes.',
        'Add carrot and zucchini, cook 5 minutes.',
        'Add crushed tomatoes, paprika and cumin.',
        'Drain and add lentils. Simmer for 10 minutes.',
        'Adjust salt and serve.',
      ],
      tiempoMinutos: 25,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch'],
      etiquetas: ['iron-rich', 'high-fiber', 'vegetarian', 'breastfeeding', 'filling'],
      notas: 'Using canned lentils saves half the time. Freezes perfectly.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'baked-salmon',
      source: 'default',
      nombre: 'Baked salmon with sweet potato and asparagus',
      descripcion: 'Rich in omega-3, ideal for breastfeeding. All in the oven, minimal effort.',
      ingredientes: [
        { nombre: 'Salmon fillets', cantidad: 2, unidad: 'units', categoria: 'protein' },
        { nombre: 'Sweet potato', cantidad: 2, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Green asparagus', cantidad: 200, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Lemon', cantidad: 1, unidad: 'unit', categoria: 'fruits' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Black pepper', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Preheat oven to 200°C / 400°F.',
        'Peel and slice sweet potatoes thinly. Place on baking sheet with oil and salt.',
        'Roast sweet potato for 15 minutes.',
        'Add asparagus and salmon to the sheet. Squeeze lemon over the top.',
        'Roast for 15 more minutes.',
      ],
      tiempoMinutos: 35,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['omega-3', 'high-protein', 'breastfeeding', 'filling'],
      notas: 'Salmon omega-3 is excellent for breastfeeding and postpartum recovery.',
      favorita: true,
      creadaEn: '2026-03-19',
    },
    {
      id: 'spinach-feta-omelette',
      source: 'default',
      nombre: 'Spinach and feta cheese omelette',
      descripcion: 'Quick, rich in iron and calcium. Perfect for a light dinner or batch cooking.',
      ingredientes: [
        { nombre: 'Egg', cantidad: 4, unidad: 'units', categoria: 'protein' },
        { nombre: 'Fresh spinach', cantidad: 150, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Feta cheese', cantidad: 80, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Onion', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Dice the onion and sauté in a pan with oil for 3 minutes.',
        'Add spinach and cook until wilted (2 minutes).',
        'Beat eggs with salt and pour into the pan.',
        'Crumble feta cheese on top.',
        'Cook on medium-low heat for 5 minutes. Flip and cook 3 more minutes.',
      ],
      tiempoMinutos: 15,
      raciones: 2,
      batchCooking: true,
      congelable: true,
      categorias: ['dinner', 'lunch'],
      etiquetas: ['quick', 'high-protein', 'iron-rich', 'calcium-rich', 'filling'],
      notas: 'Can be eaten cold the next day. Great for having dinners ready in advance.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'chicken-avocado-wrap',
      source: 'default',
      nombre: 'Chicken, avocado and yogurt wrap',
      descripcion: 'Quick and healthy meal. Perfect for eating with one hand.',
      ingredientes: [
        { nombre: 'Whole wheat tortilla', cantidad: 2, unidad: 'units', categoria: 'grains' },
        { nombre: 'Cooked chicken breast', cantidad: 200, unidad: 'g', categoria: 'protein' },
        { nombre: 'Ripe avocado', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Plain yogurt', cantidad: 2, unidad: 'tbsp', categoria: 'dairy' },
        { nombre: 'Lettuce', cantidad: 4, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Tomato', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Lemon juice', cantidad: 1, unidad: 'tbsp', categoria: 'fruits' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Shred the cooked chicken.',
        'Mash the avocado with lemon and salt.',
        'Spread yogurt on the tortilla, then the avocado.',
        'Add chicken, lettuce and sliced tomato.',
        'Roll tightly and cut in half.',
      ],
      tiempoMinutos: 10,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch'],
      etiquetas: ['quick', 'high-protein', 'filling'],
      notas: 'Tip: cook extra chicken during Sunday batch cooking for easy wraps during the week.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'chickpea-spinach-saute',
      source: 'default',
      nombre: 'Sautéed chickpeas with spinach and egg',
      descripcion: 'Complete meal in 15 minutes. Plant protein + iron + egg.',
      ingredientes: [
        { nombre: 'Canned chickpeas', cantidad: 1, unidad: 'can', categoria: 'grains' },
        { nombre: 'Fresh spinach', cantidad: 150, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Egg', cantidad: 2, unidad: 'units', categoria: 'protein' },
        { nombre: 'Garlic', cantidad: 2, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Sweet paprika', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Sauté sliced garlic in a pan with oil.',
        'Add drained chickpeas and sauté for 3 minutes.',
        'Add spinach and cook until wilted.',
        'Sprinkle with paprika and stir.',
        'Make a well and fry the eggs sunny-side up next to the chickpeas.',
        'Serve with eggs on top.',
      ],
      tiempoMinutos: 15,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'iron-rich', 'high-protein', 'high-fiber', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'chicken-veggie-rice',
      source: 'default',
      nombre: 'Chicken and vegetable rice (meal prep)',
      descripcion: 'The classic meal prep. Cook in bulk and it lasts all week.',
      ingredientes: [
        { nombre: 'Brown rice', cantidad: 300, unidad: 'g', categoria: 'grains' },
        { nombre: 'Chicken breast', cantidad: 500, unidad: 'g', categoria: 'protein' },
        { nombre: 'Red bell pepper', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Zucchini', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Carrot', cantidad: 2, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Onion', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Soy sauce', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Cook brown rice according to package instructions.',
        'Dice chicken and cook in a large pan with oil. Set aside.',
        'In the same pan, sauté diced onion, pepper, zucchini and carrot.',
        'Add cooked rice and chicken. Add soy sauce.',
        'Stir well and cook 2-3 more minutes.',
        'Divide into containers for the week.',
      ],
      tiempoMinutos: 40,
      raciones: 5,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch'],
      etiquetas: ['high-protein', 'high-fiber', 'filling'],
      notas: 'Perfect for Sunday batch cooking. 5 lunches sorted.',
      favorita: true,
      creadaEn: '2026-03-19',
    },
    {
      id: 'quinoa-salad-bowl',
      source: 'default',
      nombre: 'Quinoa salad bowl',
      descripcion: 'Fresh, complete and can be prepared in advance.',
      ingredientes: [
        { nombre: 'Quinoa', cantidad: 200, unidad: 'g', categoria: 'grains' },
        { nombre: 'Cucumber', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Tomato', cantidad: 2, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Ripe avocado', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Feta cheese', cantidad: 80, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Black olives', cantidad: 50, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 3, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Lemon', cantidad: 1, unidad: 'unit', categoria: 'fruits' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Cook quinoa according to instructions (about 15 minutes). Drain and let cool.',
        'Dice cucumber, tomatoes and avocado.',
        'Mix quinoa with vegetables.',
        'Add olives and crumbled feta cheese.',
        'Dress with olive oil and lemon juice.',
      ],
      tiempoMinutos: 25,
      raciones: 3,
      batchCooking: true,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'high-protein', 'high-fiber', 'filling'],
      notas: 'Cooked quinoa keeps 5 days in the fridge. Cook quinoa in batch and assemble salads fresh.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'pasta-broccoli-pesto',
      source: 'default',
      nombre: 'Whole wheat pasta with broccoli pesto',
      descripcion: 'Nutritious pasta version. Broccoli pesto provides iron and calcium.',
      ingredientes: [
        { nombre: 'Whole wheat pasta (penne or fusilli)', cantidad: 250, unidad: 'g', categoria: 'grains' },
        { nombre: 'Broccoli', cantidad: 300, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Garlic', cantidad: 1, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Grated parmesan', cantidad: 40, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Walnuts', cantidad: 30, unidad: 'g', categoria: 'other' },
        { nombre: 'Extra virgin olive oil', cantidad: 3, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Cook pasta according to instructions.',
        'Steam or boil broccoli for 5 minutes.',
        'Blend broccoli with garlic, walnuts, parmesan and olive oil into a pesto.',
        'Toss pasta with broccoli pesto.',
        'Serve with extra parmesan on top.',
      ],
      tiempoMinutos: 20,
      raciones: 3,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'calcium-rich', 'iron-rich'],
      notas: 'The pesto can be batch-made and frozen in ice cube trays.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'homemade-hummus',
      source: 'default',
      nombre: 'Homemade hummus',
      descripcion: 'Perfect snack: filling, nutritious and ready in 5 minutes.',
      ingredientes: [
        { nombre: 'Canned chickpeas', cantidad: 1, unidad: 'can', categoria: 'grains' },
        { nombre: 'Tahini (sesame paste)', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Lemon', cantidad: 1, unidad: 'unit', categoria: 'fruits' },
        { nombre: 'Garlic', cantidad: 1, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 3, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Cumin', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Water', cantidad: 3, unidad: 'tbsp', categoria: 'other' },
      ],
      pasos: [
        'Drain chickpeas and reserve some liquid.',
        'Blend all ingredients in a food processor until smooth.',
        'Add water or chickpea liquid if too thick.',
        'Serve with a drizzle of oil and paprika on top.',
      ],
      tiempoMinutos: 5,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['snack'],
      etiquetas: ['quick', 'vegetarian', 'high-protein', 'high-fiber', 'filling'],
      notas: 'Serve with carrot sticks, cucumber or whole wheat bread. Keeps 5 days in the fridge.',
      favorita: true,
      creadaEn: '2026-03-19',
    },
    {
      id: 'greek-yogurt-granola',
      source: 'default',
      nombre: 'Greek yogurt with fruit and granola',
      descripcion: 'Quick snack rich in protein and calcium. Ideal for mid-morning or afternoon.',
      ingredientes: [
        { nombre: 'Plain Greek yogurt', cantidad: 200, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Banana', cantidad: 1, unidad: 'unit', categoria: 'fruits' },
        { nombre: 'Sugar-free granola', cantidad: 30, unidad: 'g', categoria: 'grains' },
        { nombre: 'Honey', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Pour yogurt into a bowl.',
        'Add sliced banana and granola.',
        'Drizzle with honey if desired.',
      ],
      tiempoMinutos: 3,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['snack', 'breakfast'],
      etiquetas: ['quick', 'high-protein', 'calcium-rich', 'breastfeeding'],
      notas: 'Swap the fruit depending on the season.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'baked-hake',
      source: 'default',
      nombre: 'Baked hake with roasted potatoes',
      descripcion: 'Mild white fish, easy to digest. Complete oven-baked meal.',
      ingredientes: [
        { nombre: 'Hake fillets', cantidad: 4, unidad: 'units', categoria: 'protein' },
        { nombre: 'Potato', cantidad: 4, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Onion', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Green bell pepper', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'White wine', cantidad: 50, unidad: 'ml', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 3, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Preheat oven to 190°C / 375°F.',
        'Thinly slice potatoes, onion and pepper.',
        'Place potatoes, onion and pepper on a baking dish with oil and salt.',
        'Roast for 25 minutes.',
        'Place hake fillets on top, drizzle with white wine.',
        'Roast for 15 more minutes.',
      ],
      tiempoMinutos: 45,
      raciones: 4,
      batchCooking: true,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['high-protein', 'breastfeeding'],
      notas: 'The alcohol from the wine evaporates during cooking.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'mushroom-asparagus-scramble',
      source: 'default',
      nombre: 'Mushroom and asparagus scramble',
      descripcion: 'Light, quick dinner rich in protein.',
      ingredientes: [
        { nombre: 'Egg', cantidad: 3, unidad: 'units', categoria: 'protein' },
        { nombre: 'Mushrooms', cantidad: 200, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Green asparagus', cantidad: 150, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Garlic', cantidad: 1, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Clean and slice mushrooms. Cut asparagus into pieces.',
        'Sauté sliced garlic in a pan with oil.',
        'Add mushrooms and cook 5 minutes until they release their water.',
        'Add asparagus and cook 3 minutes.',
        'Beat eggs with salt and add to the pan.',
        'Stir gently until set but still creamy.',
      ],
      tiempoMinutos: 15,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner'],
      etiquetas: ['quick', 'high-protein', 'filling'],
      notas: 'Great with a slice of whole wheat toast on the side.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'date-oat-energy-balls',
      source: 'default',
      nombre: 'Date and oat energy balls',
      descripcion: 'No-added-sugar energy snack. Ready in 10 minutes and lasts all week.',
      ingredientes: [
        { nombre: 'Medjool dates', cantidad: 150, unidad: 'g', categoria: 'fruits' },
        { nombre: 'Rolled oats', cantidad: 100, unidad: 'g', categoria: 'grains' },
        { nombre: 'Peanut butter', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Cocoa powder', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Shredded coconut', cantidad: 30, unidad: 'g', categoria: 'pantry' },
      ],
      pasos: [
        'Blend pitted dates in a food processor until a paste forms.',
        'Add oats, peanut butter and cocoa. Mix well.',
        'Roll into small balls with your hands.',
        'Coat in shredded coconut.',
        'Refrigerate at least 30 minutes before eating.',
      ],
      tiempoMinutos: 10,
      raciones: 12,
      batchCooking: true,
      congelable: true,
      categorias: ['snack'],
      etiquetas: ['quick', 'vegetarian', 'high-fiber', 'breastfeeding', 'filling'],
      notas: 'Keeps 7 days in the fridge, 1 month in the freezer. Perfect for snacking between feeds.',
      favorita: true,
      creadaEn: '2026-03-19',
    },
    {
      id: 'turkey-stir-fry',
      source: 'default',
      nombre: 'Turkey stir-fry with vegetables and rice',
      descripcion: 'Lean protein with mixed vegetables. Quick wok-style.',
      ingredientes: [
        { nombre: 'Turkey breast', cantidad: 400, unidad: 'g', categoria: 'protein' },
        { nombre: 'Basmati rice', cantidad: 200, unidad: 'g', categoria: 'grains' },
        { nombre: 'Red bell pepper', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Zucchini', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Onion', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Soy sauce', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Fresh ginger', cantidad: 1, unidad: 'tsp', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
      ],
      pasos: [
        'Cook rice according to instructions.',
        'Slice turkey into strips and julienne the vegetables.',
        'Stir-fry turkey in a large pan or wok with oil on high heat for 4 minutes.',
        'Add vegetables and ginger. Stir-fry 4-5 minutes.',
        'Add soy sauce and toss.',
        'Serve over rice.',
      ],
      tiempoMinutos: 25,
      raciones: 3,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['high-protein', 'quick', 'filling'],
      notas: 'Turkey is very lean and protein-rich. Great for weight loss without going hungry.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'mixed-veggie-cream-soup',
      source: 'default',
      nombre: 'Mixed vegetable cream soup (wildcard)',
      descripcion: 'The perfect wildcard recipe: any vegetables you have at home will work.',
      ingredientes: [
        { nombre: 'Zucchini', cantidad: 2, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Leek', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Potato', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Carrot', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Cream cheese wedge', cantidad: 1, unidad: 'unit', categoria: 'dairy' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Wash and chop all vegetables.',
        'Sauté leek in a pot with oil for 3 minutes.',
        'Add the rest of the vegetables and cover with water.',
        'Cook for 20 minutes on medium heat.',
        'Blend with the cream cheese for a creamy texture.',
        'Adjust salt.',
      ],
      tiempoMinutos: 30,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['dinner', 'lunch'],
      etiquetas: ['vegetarian', 'high-fiber', 'breastfeeding', 'filling'],
      notas: 'Works with any vegetables: green beans, cauliflower, spinach... Can be frozen in portions.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    // ── STAPLES ──
    {
      id: 'white-rice',
      source: 'default',
      nombre: 'White rice',
      descripcion: 'Basic fluffy white rice. A staple side for any meal.',
      ingredientes: [
        { nombre: 'White rice', cantidad: 200, unidad: 'g', categoria: 'grains' },
        { nombre: 'Water', cantidad: 400, unidad: 'ml', categoria: 'other' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Rinse rice under cold water until the water runs clear.',
        'Bring water to a boil with salt and a drizzle of oil.',
        'Add rice, stir once, cover and reduce to low heat.',
        'Cook for 15 minutes without lifting the lid.',
        'Remove from heat and let sit covered for 5 minutes. Fluff with a fork.',
      ],
      tiempoMinutos: 20,
      raciones: 3,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'gluten-free'],
      notas: 'Cook a big batch on Sunday and refrigerate. Keeps 4-5 days in the fridge.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'grilled-pork-shoulder',
      source: 'default',
      nombre: 'Grilled pork shoulder steaks',
      descripcion: 'Simple grilled pork shoulder steaks. Quick protein, ready in minutes.',
      ingredientes: [
        { nombre: 'Pork shoulder steaks', cantidad: 4, unidad: 'units', categoria: 'protein' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Garlic', cantidad: 1, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Black pepper', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Season pork loin steaks with salt and pepper on both sides.',
        'Heat a pan or griddle on high heat with a drizzle of oil.',
        'Add the garlic clove to flavor the oil, then remove it.',
        'Cook steaks 2-3 minutes per side until golden.',
        'Let rest 1 minute before serving.',
      ],
      tiempoMinutos: 10,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'high-protein', 'gluten-free'],
      notas: 'Pair with rice, salad or roasted vegetables for a complete meal.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'scrambled-eggs-mushrooms',
      source: 'default',
      nombre: 'Scrambled eggs with mushrooms',
      descripcion: 'Simple, comforting scramble. Great for a quick dinner or lunch.',
      ingredientes: [
        { nombre: 'Egg', cantidad: 3, unidad: 'units', categoria: 'protein' },
        { nombre: 'Mushrooms', cantidad: 150, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Clean and slice mushrooms.',
        'Sauté mushrooms in a pan with oil on medium-high heat for 4-5 minutes.',
        'Beat eggs with a pinch of salt.',
        'Pour eggs over the mushrooms, stir gently until just set but still creamy.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner', 'lunch'],
      etiquetas: ['quick', 'high-protein', 'gluten-free', 'filling'],
      notas: 'Add a slice of whole wheat toast on the side.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'grilled-chicken-breast',
      source: 'default',
      nombre: 'Grilled chicken breast',
      descripcion: 'The ultimate staple protein. Season however you like.',
      ingredientes: [
        { nombre: 'Chicken breast', cantidad: 2, unidad: 'units', categoria: 'protein' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Black pepper', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Dried oregano', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Butterfly or pound chicken breasts to even thickness.',
        'Season both sides with salt, pepper and oregano.',
        'Heat a pan or griddle on medium-high heat with oil.',
        'Cook 4-5 minutes per side until golden and cooked through.',
        'Let rest 2 minutes, then slice.',
      ],
      tiempoMinutos: 12,
      raciones: 2,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'high-protein', 'gluten-free'],
      notas: 'Cook 4-5 breasts on Sunday for wraps, salads and bowls during the week.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'steamed-broccoli',
      source: 'default',
      nombre: 'Steamed broccoli',
      descripcion: 'Simple steamed broccoli. Perfect side dish, rich in calcium and iron.',
      ingredientes: [
        { nombre: 'Broccoli', cantidad: 400, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Lemon juice', cantidad: 1, unidad: 'tsp', categoria: 'fruits' },
      ],
      pasos: [
        'Cut broccoli into florets.',
        'Steam for 5-6 minutes until tender but still bright green.',
        'Drizzle with olive oil, lemon and salt.',
      ],
      tiempoMinutos: 8,
      raciones: 2,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'vegetarian', 'calcium-rich', 'iron-rich', 'gluten-free'],
      notas: 'Works as a side for any protein. Also great in salads, pastas or bowls.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'pan-fried-eggs',
      source: 'default',
      nombre: 'Pan-fried eggs (sunny side up)',
      descripcion: 'The simplest protein. Ready in 3 minutes.',
      ingredientes: [
        { nombre: 'Egg', cantidad: 2, unidad: 'units', categoria: 'protein' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Heat a non-stick pan on medium heat with oil.',
        'Crack eggs into the pan.',
        'Cook 2-3 minutes until whites are set but yolk is still runny.',
        'Season with salt.',
      ],
      tiempoMinutos: 3,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['breakfast', 'lunch', 'dinner'],
      etiquetas: ['quick', 'high-protein', 'gluten-free'],
      notas: 'Top on rice, toast, salads or alongside any meal for extra protein.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'green-beans-garlic',
      source: 'default',
      nombre: 'Sautéed green beans with garlic',
      descripcion: 'Quick vegetable side. Garlic makes everything better.',
      ingredientes: [
        { nombre: 'Green beans', cantidad: 300, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Garlic', cantidad: 2, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Trim and halve the green beans.',
        'Boil in salted water for 4 minutes. Drain.',
        'Sauté sliced garlic in a pan with oil until golden.',
        'Add beans and toss for 2 minutes. Season with salt.',
      ],
      tiempoMinutos: 10,
      raciones: 2,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'vegetarian', 'high-fiber', 'gluten-free'],
      notas: 'Great side for any grilled protein.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'basic-green-salad',
      source: 'default',
      nombre: 'Basic green salad',
      descripcion: 'Simple mixed salad. Add whatever you have in the fridge.',
      ingredientes: [
        { nombre: 'Mixed salad leaves', cantidad: 100, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Tomato', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Cucumber', cantidad: 0.5, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Vinegar or lemon', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Wash and dry salad leaves.',
        'Dice tomato and slice cucumber.',
        'Toss everything in a bowl.',
        'Dress with oil, vinegar/lemon and salt.',
      ],
      tiempoMinutos: 5,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'vegetarian', 'gluten-free'],
      notas: 'Add canned tuna, cheese, olives, corn or avocado for a more complete salad.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'whole-wheat-pasta',
      source: 'default',
      nombre: 'Whole wheat pasta (plain)',
      descripcion: 'Basic cooked pasta, ready for any sauce or topping.',
      ingredientes: [
        { nombre: 'Whole wheat pasta', cantidad: 200, unidad: 'g', categoria: 'grains' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Bring a large pot of salted water to a boil.',
        'Add pasta and cook according to package instructions (usually 10-12 min).',
        'Drain and toss with a little olive oil to prevent sticking.',
      ],
      tiempoMinutos: 15,
      raciones: 2,
      batchCooking: true,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'vegetarian', 'high-fiber'],
      notas: 'Top with pesto, tomato sauce, sautéed vegetables or grilled chicken.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'homemade-tomato-sauce',
      source: 'default',
      nombre: 'Tomato sauce (homemade)',
      descripcion: 'Simple tomato sauce for pasta, rice or as a base for other dishes.',
      ingredientes: [
        { nombre: 'Crushed tomatoes', cantidad: 400, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Onion', cantidad: 0.5, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Garlic', cantidad: 1, unidad: 'clove', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Dried oregano', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Finely dice onion and garlic.',
        'Sauté in a pan with oil for 3 minutes until soft.',
        'Add crushed tomatoes, oregano and salt.',
        'Simmer on low heat for 15 minutes, stirring occasionally.',
      ],
      tiempoMinutos: 20,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'gluten-free'],
      notas: 'Make a big batch and freeze in portions. Use for pasta, pizza, eggs, rice...',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'roasted-sweet-potato',
      source: 'default',
      nombre: 'Roasted sweet potato',
      descripcion: 'Easy oven-roasted sweet potato. Naturally sweet and filling.',
      ingredientes: [
        { nombre: 'Sweet potato', cantidad: 2, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Preheat oven to 200°C / 400°F.',
        'Peel and cut sweet potatoes into cubes or wedges.',
        'Toss with oil and salt on a baking sheet.',
        'Roast for 25-30 minutes, turning halfway, until golden and tender.',
      ],
      tiempoMinutos: 35,
      raciones: 2,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'gluten-free', 'high-fiber', 'filling'],
      notas: 'Great as a side or as a base for bowls. Can also microwave whole for 6-8 min.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'canned-tuna-salad',
      source: 'default',
      nombre: 'Canned tuna salad',
      descripcion: 'No-cook protein in 2 minutes. Perfect for when you have zero energy.',
      ingredientes: [
        { nombre: 'Canned tuna in olive oil', cantidad: 1, unidad: 'can', categoria: 'protein' },
        { nombre: 'Tomato', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Corn (canned)', cantidad: 50, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Extra virgin olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Drain tuna and place in a bowl.',
        'Dice tomato and add to the bowl.',
        'Add corn, oil and salt. Mix.',
      ],
      tiempoMinutos: 3,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'high-protein', 'gluten-free'],
      notas: 'Eat on its own, on toast, in a wrap or over rice. Lifesaver on exhausting days.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    {
      id: 'boiled-eggs',
      source: 'default',
      nombre: 'Boiled eggs',
      descripcion: 'Batch-cook a dozen for the week. Ready-to-eat protein anytime.',
      ingredientes: [
        { nombre: 'Egg', cantidad: 6, unidad: 'units', categoria: 'protein' },
        { nombre: 'Water', cantidad: 1, unidad: 'l', categoria: 'other' },
      ],
      pasos: [
        'Place eggs in a pot and cover with cold water.',
        'Bring to a boil.',
        'Once boiling, cook 10 minutes for hard-boiled (7 min for soft-boiled).',
        'Transfer to ice water to stop cooking. Peel when cool.',
      ],
      tiempoMinutos: 15,
      raciones: 6,
      batchCooking: true,
      congelable: false,
      categorias: ['breakfast', 'snack', 'lunch'],
      etiquetas: ['quick', 'high-protein', 'gluten-free'],
      notas: 'Keep unpeeled in the fridge for up to 7 days. Great for salads, snacks or breakfast.',
      favorita: false,
      creadaEn: '2026-03-19',
    },
    // ═══════════════════════════════════════════════
    // FRUCTOSE DIET (Dietpro) RECIPES
    // ═══════════════════════════════════════════════
    {
      id: 'dietpro-chia-strawberry-cocoa',
      source: 'dietpro',
      nombre: 'Chia Pudding with Coconut Milk, Strawberries & Cocoa (Dietpro)',
      descripcion: 'Creamy chia pudding with tropical coconut milk, fresh strawberries and a touch of cocoa.',
      ingredientes: [
        { nombre: 'Coconut milk', cantidad: 200, unidad: 'ml', categoria: 'dairy' },
        { nombre: 'Chia seeds', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Strawberries', cantidad: 5, unidad: 'units', categoria: 'fruits' },
        { nombre: 'Unsweetened cocoa powder', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Put chia seeds in a bowl with some coconut milk. Mix well and refrigerate for 2-3 hours or overnight.',
        'Add remaining coconut milk and cocoa powder, mix, and top with sliced strawberries.',
      ],
      tiempoMinutos: 5,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['breakfast'],
      etiquetas: ['quick', 'high-fiber', 'gluten-free', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-chia-walnut-blueberry',
      source: 'dietpro',
      nombre: 'Chia Pudding with Coconut Milk, Walnuts & Blueberries (Dietpro)',
      descripcion: 'Overnight chia pudding topped with crunchy walnuts and antioxidant-rich blueberries.',
      ingredientes: [
        { nombre: 'Coconut milk', cantidad: 200, unidad: 'ml', categoria: 'dairy' },
        { nombre: 'Chia seeds', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Walnuts', cantidad: 1, unidad: 'unit', categoria: 'other' },
        { nombre: 'Blueberries', cantidad: 20, unidad: 'units', categoria: 'fruits' },
      ],
      pasos: [
        'Put chia seeds in a bowl with some coconut milk. Mix well and refrigerate for 2-3 hours or overnight.',
        'Add remaining coconut milk, walnuts and blueberries.',
        'Mix and serve.',
      ],
      tiempoMinutos: 5,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['breakfast'],
      etiquetas: ['quick', 'high-fiber', 'omega-3', 'gluten-free', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-toast-serrano',
      source: 'dietpro',
      nombre: 'Whole Wheat Toast with Serrano Ham (Dietpro)',
      descripcion: 'Simple toasted bread drizzled with olive oil and topped with serrano ham.',
      ingredientes: [
        { nombre: 'Whole wheat bread', cantidad: 60, unidad: 'g', categoria: 'grains' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Serrano ham', cantidad: 2, unidad: 'slices', categoria: 'protein' },
      ],
      pasos: [
        'Toast bread.',
        'Drizzle with olive oil and top with serrano ham.',
      ],
      tiempoMinutos: 5,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['snack'],
      etiquetas: ['quick', 'high-protein', 'iron-rich'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-chickpea-salad',
      source: 'dietpro',
      nombre: 'Chickpea Salad with Lime, Leek, Lamb\'s Lettuce, Avocado & Tuna (Dietpro)',
      descripcion: 'Protein-packed chickpea salad with fresh vegetables, tuna and a zesty lime-cumin dressing.',
      ingredientes: [
        { nombre: 'Cooked chickpeas', cantidad: 150, unidad: 'g', categoria: 'grains' },
        { nombre: 'Avocado', cantidad: 0.5, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Leek', cantidad: 3, unidad: 'slices', categoria: 'vegetables' },
        { nombre: 'Lamb\'s lettuce', cantidad: 60, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Canned tuna', cantidad: 1, unidad: 'can', categoria: 'protein' },
        { nombre: 'Lime juice', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Cumin', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Put rinsed cooked chickpeas in a bowl.',
        'Add leek, lamb\'s lettuce, avocado and tuna.',
        'Season with salt, pepper, lime juice and cumin.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch'],
      etiquetas: ['quick', 'high-protein', 'high-fiber', 'iron-rich', 'filling', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-spinach-omelette',
      source: 'dietpro',
      nombre: 'Spinach Omelette (Dietpro)',
      descripcion: 'Simple and nutritious omelette loaded with sautéed spinach.',
      ingredientes: [
        { nombre: 'Eggs', cantidad: 2, unidad: 'units', categoria: 'protein' },
        { nombre: 'Spinach', cantidad: 80, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
      ],
      pasos: [
        'Wash spinach and sauté in a pan with olive oil.',
        'Beat eggs and pour over spinach.',
        'Cook until set, flipping once.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner'],
      etiquetas: ['quick', 'high-protein', 'iron-rich', 'gluten-free', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-porridge-blueberries',
      source: 'dietpro',
      nombre: 'Porridge with Oat Milk, Blueberries & Walnuts (Dietpro)',
      descripcion: 'Warm and comforting oat porridge topped with blueberries and walnuts.',
      ingredientes: [
        { nombre: 'Oat milk', cantidad: 250, unidad: 'ml', categoria: 'dairy' },
        { nombre: 'Rolled oats', cantidad: 60, unidad: 'g', categoria: 'grains' },
        { nombre: 'Blueberries', cantidad: 40, unidad: 'units', categoria: 'fruits' },
        { nombre: 'Walnuts', cantidad: 5, unidad: 'units', categoria: 'other' },
      ],
      pasos: [
        'Heat oat milk in a saucepan. When boiling, add oats and cook on low heat for 5 minutes, stirring constantly.',
        'When it thickens into porridge, remove from heat. Add more oat milk if too thick.',
        'Top with blueberries and chopped walnuts.',
        'Can be prepared the night before and refrigerated.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['breakfast', 'snack'],
      etiquetas: ['quick', 'high-fiber', 'omega-3', 'filling', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-potato-zucchini-salad',
      source: 'dietpro',
      nombre: 'Potato, Zucchini & Fresh Cheese Salad (Dietpro)',
      descripcion: 'Light salad with boiled potatoes, blanched zucchini ribbons, grated tomato and fresh cheese.',
      ingredientes: [
        { nombre: 'Potato', cantidad: 1, unidad: 'medium unit', categoria: 'vegetables' },
        { nombre: 'Zucchini', cantidad: 0.5, unidad: 'small', categoria: 'vegetables' },
        { nombre: 'Tomato', cantidad: 1, unidad: 'small', categoria: 'vegetables' },
        { nombre: 'Fresh cheese 0% fat', cantidad: 80, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Boil potatoes whole with skin. When soft, peel and slice thickly.',
        'Cut zucchini into thin strips with a peeler. Blanch in boiling water for 2 minutes.',
        'Plate potato slices as base, add grated tomato, zucchini and diced fresh cheese.',
        'Dress with olive oil.',
      ],
      tiempoMinutos: 25,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch'],
      etiquetas: ['vegetarian', 'calcium-rich', 'gluten-free', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-asparagus-cream-langoustine',
      source: 'dietpro',
      nombre: 'Cold Asparagus Cream Shots with Langoustine Tails (Dietpro)',
      descripcion: 'Elegant cold asparagus cream served in shot glasses with langoustine tails.',
      ingredientes: [
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Vinegar', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'White asparagus', cantidad: 7, unidad: 'medium spears', categoria: 'vegetables' },
        { nombre: 'Langoustines', cantidad: 4, unidad: 'units', categoria: 'protein' },
      ],
      pasos: [
        'Drain asparagus well and place chopped in a blender. Add olive oil and vinegar, blend until smooth.',
        'Pour cream into small glasses and place two cooked, peeled langoustine tails on the rim.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner'],
      etiquetas: ['quick', 'high-protein', 'gluten-free'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-toast-turkey',
      source: 'dietpro',
      nombre: 'Whole Wheat Toast with Turkey & Olive Oil (Dietpro)',
      descripcion: 'Hearty toasted bread with olive oil and turkey breast slices.',
      ingredientes: [
        { nombre: 'Whole wheat bread', cantidad: 120, unidad: 'g', categoria: 'grains' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Turkey breast slices', cantidad: 5, unidad: 'slices', categoria: 'protein' },
      ],
      pasos: [
        'Toast bread.',
        'Drizzle with olive oil and top with turkey slices.',
      ],
      tiempoMinutos: 5,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['snack'],
      etiquetas: ['quick', 'high-protein'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-salmon-mustard',
      source: 'dietpro',
      nombre: 'Salmon with Creamy Mustard Sauce (Dietpro)',
      descripcion: 'Grilled salmon fillet topped with a smooth onion-mustard cream sauce.',
      ingredientes: [
        { nombre: 'Onion', cantidad: 0.33, unidad: 'small', categoria: 'vegetables' },
        { nombre: 'Salmon fillet', cantidad: 1, unidad: 'piece', categoria: 'protein' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Evaporated milk', cantidad: 2, unidad: 'tbsp', categoria: 'dairy' },
        { nombre: 'Mustard', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Finely chop onion and sauté in olive oil until golden. Add mustard and evaporated milk. Cook for 5-6 minutes. Remove and blend.',
        'Grill salmon fillet.',
        'Plate salmon and top with mustard sauce.',
      ],
      tiempoMinutos: 20,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch'],
      etiquetas: ['high-protein', 'omega-3', 'gluten-free', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-corn-quesadillas',
      source: 'dietpro',
      nombre: 'Corn Quesadillas with Scrambled Eggs & Avocado (Dietpro)',
      descripcion: 'Crispy corn tortilla quesadillas filled with scrambled egg, avocado, cilantro and melted cheese.',
      ingredientes: [
        { nombre: 'Corn tortillas', cantidad: 2, unidad: 'units', categoria: 'grains' },
        { nombre: 'Egg', cantidad: 1, unidad: 'unit', categoria: 'protein' },
        { nombre: 'Avocado', cantidad: 0.25, unidad: 'piece', categoria: 'vegetables' },
        { nombre: 'Cilantro', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Gruyere cheese', cantidad: 1.5, unidad: 'slices', categoria: 'dairy' },
      ],
      pasos: [
        'Beat egg and scramble in a lightly oiled pan.',
        'Fill each tortilla with scrambled egg, diced avocado, chopped cilantro and grated cheese.',
        'Fold tortilla in half twice into a triangle and cook on a griddle until lightly golden and cheese melts.',
      ],
      tiempoMinutos: 15,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner'],
      etiquetas: ['high-protein', 'calcium-rich', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-toast-egg-avocado',
      source: 'dietpro',
      nombre: 'Toast with Scrambled Eggs & Avocado (Dietpro)',
      descripcion: 'Toasted bread topped with fluffy scrambled eggs and creamy avocado slices.',
      ingredientes: [
        { nombre: 'White bread', cantidad: 50, unidad: 'g', categoria: 'grains' },
        { nombre: 'Egg', cantidad: 1, unidad: 'unit', categoria: 'protein' },
        { nombre: 'Avocado', cantidad: 0.25, unidad: 'piece', categoria: 'vegetables' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Peel and thinly slice avocado.',
        'Beat egg and scramble in a pan with oil.',
        'Place scrambled egg on toasted bread and top with avocado slices.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['snack'],
      etiquetas: ['quick', 'high-protein', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-lentil-salad',
      source: 'dietpro',
      nombre: 'Lentil & Lamb\'s Lettuce Salad with Avocado & Pumpkin Seeds (Dietpro)',
      descripcion: 'Hearty lentil salad on a bed of lamb\'s lettuce with avocado and pumpkin seeds.',
      ingredientes: [
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Lamb\'s lettuce', cantidad: 60, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Avocado', cantidad: 9, unidad: 'thin slices', categoria: 'vegetables' },
        { nombre: 'Pumpkin seeds', cantidad: 1, unidad: 'tbsp', categoria: 'other' },
        { nombre: 'Cooked lentils', cantidad: 150, unidad: 'g', categoria: 'grains' },
      ],
      pasos: [
        'Drain cooked lentils and rinse under cold water.',
        'Plate lamb\'s lettuce as base, add sliced avocado and lentils. Top with pumpkin seeds.',
        'Dress with olive oil.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch'],
      etiquetas: ['quick', 'high-fiber', 'iron-rich', 'vegetarian', 'filling', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-vegetable-cream-soup',
      source: 'dietpro',
      nombre: 'Vegetable Cream Soup with Turkey/Chicken Cold Cuts (Dietpro)',
      descripcion: 'Silky blended vegetable soup with carrot, zucchini, squash, leek and cauliflower, served with turkey cold cuts.',
      ingredientes: [
        { nombre: 'Carrot', cantidad: 1.5, unidad: 'large', categoria: 'vegetables' },
        { nombre: 'Zucchini', cantidad: 0.5, unidad: 'medium', categoria: 'vegetables' },
        { nombre: 'Butternut squash', cantidad: 200, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Leek', cantidad: 1.5, unidad: 'medium', categoria: 'vegetables' },
        { nombre: 'Cauliflower', cantidad: 200, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Turkey breast slices', cantidad: 3, unidad: 'slices', categoria: 'protein' },
      ],
      pasos: [
        'Chop carrot, squash, zucchini, leek and cauliflower into small pieces.',
        'Sauté leek in oil, add chopped vegetables, cover with water, season with salt, pepper and nutmeg.',
        'Boil until tender, then blend until smooth. Serve with turkey/chicken cold cuts on the side.',
      ],
      tiempoMinutos: 30,
      raciones: 2,
      batchCooking: true,
      congelable: true,
      categorias: ['dinner'],
      etiquetas: ['high-fiber', 'high-protein', 'gluten-free', 'filling', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-rice-zucchini-chicken',
      source: 'dietpro',
      nombre: 'Rice with Zucchini & Chicken (Dietpro)',
      descripcion: 'Simple rice dish with sautéed zucchini and seasoned chicken breast.',
      ingredientes: [
        { nombre: 'White rice', cantidad: 90, unidad: 'g', categoria: 'grains' },
        { nombre: 'Zucchini', cantidad: 0.5, unidad: 'medium', categoria: 'vegetables' },
        { nombre: 'Chicken breast', cantidad: 1, unidad: 'fillet', categoria: 'protein' },
        { nombre: 'Black pepper', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Salt', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Cook rice in a saucepan with double the water for 15-20 minutes. Drain and set aside.',
        'Peel zucchini and dice. Cut chicken into similar-sized pieces and season.',
        'Sauté zucchini and chicken in a pan with oil. When chicken is golden and zucchini tender, add rice and mix for a few minutes.',
        'Add herbs or spices to taste before serving.',
      ],
      tiempoMinutos: 25,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch'],
      etiquetas: ['high-protein', 'filling', 'gluten-free'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-ricotta-strawberry',
      source: 'dietpro',
      nombre: 'Ricotta Cups with Strawberry Sauce (Dietpro)',
      descripcion: 'Light ricotta cream cups topped with a fresh strawberry-orange sauce.',
      ingredientes: [
        { nombre: 'Sweetener', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Cream cheese', cantidad: 1, unidad: 'tbsp', categoria: 'dairy' },
        { nombre: 'Ricotta', cantidad: 100, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Strawberries', cantidad: 8, unidad: 'units', categoria: 'fruits' },
        { nombre: 'Orange juice', cantidad: 3, unidad: 'tbsp', categoria: 'fruits' },
        { nombre: 'Vanilla extract', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Place ricotta in a fine sieve and press out liquid. Mix in a bowl with cream cheese, vanilla and sweetener.',
        'Whisk until creamy and uniform. Fill cups halfway and refrigerate for at least 30 minutes.',
        'Chop strawberries (reserve one), blend with orange juice to make sauce.',
        'Top ricotta cream with strawberry sauce and garnish with reserved strawberry quartered.',
        'Refrigerate until serving.',
      ],
      tiempoMinutos: 15,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['snack'],
      etiquetas: ['calcium-rich', 'gluten-free', 'breastfeeding'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-salmon-mango-tartare',
      source: 'dietpro',
      nombre: 'Smoked Salmon, Mango & Avocado Tartare (Dietpro)',
      descripcion: 'Elegant layered tartare with smoked salmon, mango and avocado dressed with soy and sesame.',
      ingredientes: [
        { nombre: 'Smoked salmon', cantidad: 4, unidad: 'thin slices', categoria: 'protein' },
        { nombre: 'Avocado', cantidad: 9, unidad: 'thin slices', categoria: 'vegetables' },
        { nombre: 'Mango', cantidad: 0.5, unidad: 'unit', categoria: 'fruits' },
        { nombre: 'Red onion', cantidad: 0.25, unidad: 'small', categoria: 'vegetables' },
        { nombre: 'Soy sauce', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Lemon juice', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Sesame seeds', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Dice avocado and chop onion. Mix in a bowl, dress with lemon, salt and pepper.',
        'In another bowl, dice smoked salmon and add soy sauce.',
        'Dice mango and set aside.',
        'Layer tartare with a mold: avocado-onion base, mango in the middle, salmon on top.',
        'Garnish with sesame seeds.',
      ],
      tiempoMinutos: 15,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner'],
      etiquetas: ['high-protein', 'omega-3', 'gluten-free'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-hake-pasta-sautee',
      source: 'dietpro',
      nombre: 'Grilled Hake with Whole Wheat Pasta, Carrot & Red Cabbage Sauté (Dietpro)',
      descripcion: 'Grilled hake fillet served alongside whole wheat pasta sautéed with red cabbage, carrot and cinnamon.',
      ingredientes: [
        { nombre: 'Hake fillet', cantidad: 1.5, unidad: 'fillets', categoria: 'protein' },
        { nombre: 'Red cabbage', cantidad: 150, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Carrot', cantidad: 1, unidad: 'large', categoria: 'vegetables' },
        { nombre: 'Whole wheat macaroni', cantidad: 100, unidad: 'g', categoria: 'grains' },
        { nombre: 'Cinnamon', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
      ],
      pasos: [
        'Cook whole wheat macaroni in salted boiling water for 12 minutes. Drain and set aside.',
        'Steam julienned red cabbage and carrot batons.',
        'Sauté vegetables in a pan with oil at high heat. Sprinkle with cinnamon and add pasta. Mix well.',
        'Grill hake fillet.',
        'Plate hake alongside the pasta and vegetable sauté.',
      ],
      tiempoMinutos: 25,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch'],
      etiquetas: ['high-protein', 'high-fiber', 'omega-3', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'dietpro-zucchini-salmon-rolls',
      source: 'dietpro',
      nombre: 'Zucchini & Smoked Salmon Rolls (Dietpro)',
      descripcion: 'Thin zucchini strips rolled with cream cheese and smoked salmon, served chilled.',
      ingredientes: [
        { nombre: 'Zucchini', cantidad: 0.5, unidad: 'large', categoria: 'vegetables' },
        { nombre: 'Smoked salmon', cantidad: 4, unidad: 'slices', categoria: 'protein' },
        { nombre: 'Cream cheese', cantidad: 2, unidad: 'tbsp', categoria: 'dairy' },
        { nombre: 'Olive oil', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Dried dill', cantidad: 1, unidad: 'to taste', categoria: 'pantry' },
      ],
      pasos: [
        'Wash zucchini and slice lengthwise into thin strips with a mandoline. They should be thin but sturdy enough to roll.',
        'Lightly oil a pan and cook zucchini strips 30 seconds per side. Season with salt. Pat dry if needed.',
        'Spread a thin layer of cream cheese on each strip.',
        'Place a strip of salmon on top and roll up carefully. Secure with a toothpick.',
        'Refrigerate until serving.',
      ],
      tiempoMinutos: 15,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner'],
      etiquetas: ['high-protein', 'omega-3', 'gluten-free'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    // --- Maria's recipes (from Word doc) ---
    {
      id: 'user-lentejas-thermomix',
      source: 'user',
      nombre: 'Lentejas estofadas (Thermomix)',
      descripcion: 'Lentejas castellanas con verduras, chorizo y jamón. Receta para Thermomix.',
      ingredientes: [
        { nombre: 'Lentejas castellanas secas', cantidad: 350, unidad: 'g', categoria: 'grains' },
        { nombre: 'Pimiento rojo', cantidad: 50, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Pimiento verde', cantidad: 50, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Zanahoria', cantidad: 50, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Cebolleta', cantidad: 50, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Cebolla', cantidad: 50, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Aceite de oliva', cantidad: 25, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Sal', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Pimentón dulce', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Pastilla de caldo de pollo', cantidad: 1, unidad: 'unit', categoria: 'pantry' },
        { nombre: 'Chorizo', cantidad: 50, unidad: 'g', categoria: 'protein' },
        { nombre: 'Jamón curado en dados', cantidad: 50, unidad: 'g', categoria: 'protein' },
      ],
      pasos: [
        'Poner las lentejas en remojo al menos 3 horas antes.',
        'Escurrirlas, lavarlas y reservarlas.',
        'Añadir al vaso las lentejas escurridas junto con el pimiento rojo, pimiento verde, zanahoria, cebolleta, cebolla, aceite, sal, pimentón, pastilla de caldo, chorizo, jamón y 900 g de agua.',
        'Programar 40 min / 100°C / giro inverso / velocidad cuchara.',
        'Comprobar si las lentejas están tiernas. Si no, programar 5 min más / 100°C / velocidad cuchara.',
        'Servir calientes.',
      ],
      tiempoMinutos: 50,
      raciones: 6,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['iron-rich', 'high-fiber', 'high-protein', 'filling'],
      notas: 'Se puede añadir o sustituir verduras por patata, calabaza, etc. Se puede reemplazar 50 g de lentejas por 50 g de arroz.',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-crema-puerro-calabacin',
      source: 'user',
      nombre: 'Crema de puerro y calabacín (Thermomix)',
      descripcion: 'Crema suave y reconfortante. 230 kcal por ración.',
      ingredientes: [
        { nombre: 'Puerro (parte blanca)', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Aceite de oliva', cantidad: 50, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Mantequilla o margarina', cantidad: 50, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Caldo de verduras o pollo', cantidad: 600, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Calabacín troceado', cantidad: 500, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Sal', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Nuez moscada', cantidad: 0.5, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Pimienta', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Leche', cantidad: 50, unidad: 'g', categoria: 'dairy' },
      ],
      pasos: [
        'Poner en el vaso el puerro troceado junto con el aceite y la mantequilla.',
        'Picar 5 segundos / velocidad 5.',
        'Sofreír 10 minutos / 120°C / velocidad cuchara.',
        'Añadir el resto de ingredientes.',
        'Cocinar 20 minutos / 100°C / velocidad 1.',
        'Triturar 1 minuto / velocidad 5-10 hasta obtener una crema fina.',
      ],
      tiempoMinutos: 25,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-crema-esparragos',
      source: 'user',
      nombre: 'Crema de espárragos (Thermomix)',
      descripcion: 'Crema fina de espárragos verdes con nata. Fácil.',
      ingredientes: [
        { nombre: 'Espárragos verdes', cantidad: 400, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Aceite de oliva virgen extra', cantidad: 25, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Cebolla', cantidad: 75, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Calabacín', cantidad: 180, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Caldo de verduras (caliente)', cantidad: 300, unidad: 'g', categoria: 'pantry' },
        { nombre: 'Sal', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Pimienta negra', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Nata 18% MG', cantidad: 75, unidad: 'g', categoria: 'dairy' },
      ],
      pasos: [
        'Lavar los espárragos, retirar la parte dura del tallo, cortarlos en 2-3 trozos y reservar las puntas por separado.',
        'Añadir aceite al vaso y programar 3 min / 120°C / velocidad 1.',
        'Incorporar las puntas de espárragos y rehogar 2 min / 120°C / giro inverso / velocidad cuchara. Retirar y reservar.',
        'Añadir la cebolla, trocear 4 seg / velocidad 4 y sofreír 4 min / 120°C / velocidad 1.',
        'Incorporar el calabacín y el resto de espárragos, trocear 4 seg / velocidad 4 y rehogar 1 min / 120°C / velocidad 1.',
        'Añadir el caldo, la sal y la pimienta. Programar 17 min / 100°C / velocidad 1.',
        'Incorporar la nata y programar 1 min / 90°C / velocidad 4.',
        'Dejar templar y triturar 2 min / velocidad 5-10 (progresivo).',
        'Servir decorando con las puntas de espárragos reservadas.',
      ],
      tiempoMinutos: 30,
      raciones: 3,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-macarrones-maria',
      source: 'user',
      nombre: 'Los macarrones de Maria',
      descripcion: 'Penne con salsa de tomate y lomo de cerdo. Receta casera.',
      ingredientes: [
        { nombre: 'Pasta tipo penne', cantidad: 300, unidad: 'g', categoria: 'grains' },
        { nombre: 'Tomate triturado (lata)', cantidad: 2, unidad: 'can', categoria: 'pantry' },
        { nombre: 'Lomo de cerdo (pork shoulder steaks)', cantidad: 1, unidad: 'unit', categoria: 'protein' },
        { nombre: 'Cebolla', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Aceite de oliva', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
      ],
      pasos: [
        'Picar la cebolla en trozos pequeños.',
        'Sofreírla con aceite de oliva a fuego medio hasta que esté dorada.',
        'Cortar el lomo en trozos pequeños.',
        'Añadir la carne a la sartén y cocinar durante 3-4 minutos, hasta que deje de estar roja.',
        'Añadir el tomate triturado.',
        'Cocinar a fuego medio-bajo durante 40 minutos, removiendo de vez en cuando.',
        'Cocer la pasta según las instrucciones del paquete.',
        'Mezclar la pasta con la salsa o servir por separado.',
      ],
      tiempoMinutos: 50,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['high-protein', 'filling'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-ensalada-burrata',
      source: 'user',
      nombre: 'Ensalada de burrata con bacon y vinagreta dulce',
      descripcion: 'Ensalada fresca con burrata, bacon crujiente y vinagreta de miel y albaricoque. Muy fácil.',
      ingredientes: [
        { nombre: 'Burrata', cantidad: 1, unidad: 'unit', categoria: 'dairy' },
        { nombre: 'Brotes variados (bolsa)', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Bacon o pancetta', cantidad: 1, unidad: 'unit', categoria: 'protein' },
        { nombre: 'Aceite de oliva', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Miel', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Mermelada de albaricoque', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
      ],
      pasos: [
        'Cocinar el bacon o pancetta en una sartén hasta que esté dorado y crujiente.',
        'En un bol, añadir los brotes variados.',
        'Incorporar la burrata entera o ligeramente abierta.',
        'Añadir el bacon caliente por encima.',
        'Preparar la salsa mezclando aceite de oliva, miel y mermelada de albaricoque al gusto.',
        'Aliñar la ensalada y servir.',
      ],
      tiempoMinutos: 12,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'high-protein', 'calcium-rich'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-ensalada-atun',
      source: 'user',
      nombre: 'Ensalada de atún',
      descripcion: 'Ensalada rápida y sencilla con lechuga, zanahoria, tomates cherry y atún.',
      ingredientes: [
        { nombre: 'Lechuga iceberg (bolsa)', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Zanahoria', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Tomates cherry', cantidad: 100, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Atún en lata', cantidad: 1, unidad: 'can', categoria: 'protein' },
      ],
      pasos: [
        'Lavar y escurrir la lechuga si es necesario.',
        'Pelar y rallar la zanahoria.',
        'Cortar los tomates cherry por la mitad.',
        'Escurrir el atún.',
        'Mezclar todos los ingredientes en un bol.',
      ],
      tiempoMinutos: 5,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'high-protein', 'omega-3', 'gluten-free'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-roasted-butternut',
      source: 'user',
      nombre: 'Roasted butternut squash',
      descripcion: 'Calabaza asada al horno con cebolla roja. Guarnición sencilla.',
      ingredientes: [
        { nombre: 'Butternut squash troceada (bolsa)', cantidad: 2, unidad: 'units', categoria: 'vegetables' },
        { nombre: 'Cebolla roja', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Aceite de oliva', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
      ],
      pasos: [
        'Precalentar el horno a 180°C.',
        'Cortar la cebolla roja en tiras.',
        'Colocar la calabaza y la cebolla en una bandeja de horno.',
        'Añadir un chorrito de aceite de oliva y mezclar bien.',
        'Hornear durante 30-45 minutos, removiendo a mitad de cocción, hasta que esté tierna y dorada.',
      ],
      tiempoMinutos: 45,
      raciones: 4,
      batchCooking: true,
      congelable: true,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['vegetarian', 'gluten-free', 'high-fiber'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-muslos-pollo-plancha',
      source: 'user',
      nombre: 'Muslos de pollo a la plancha',
      descripcion: 'Muslos de pollo dorados a la plancha. Muy fácil, 15-20 min.',
      ingredientes: [
        { nombre: 'Muslos de pollo deshuesados', cantidad: 6, unidad: 'units', categoria: 'protein' },
        { nombre: 'Aceite de oliva', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Sal', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Pimienta', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Salpimentar los muslos de pollo.',
        'Calentar una sartén o plancha con un poco de aceite de oliva a fuego medio-alto.',
        'Colocar el pollo con la piel hacia abajo (si tiene piel).',
        'Cocinar durante 6-8 minutos por lado, hasta que esté bien dorado y hecho por dentro.',
        'Servir caliente (opcional: añadir un chorrito de limón al final).',
      ],
      tiempoMinutos: 20,
      raciones: 3,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'high-protein', 'gluten-free'],
      notas: 'Opcional: ajo en polvo, pimentón, limón.',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-revuelto-champinones',
      source: 'user',
      nombre: 'Revuelto de champiñones',
      descripcion: 'Revuelto jugoso de champiñones con huevos y ajo.',
      ingredientes: [
        { nombre: 'Champiñones frescos', cantidad: 250, unidad: 'g', categoria: 'vegetables' },
        { nombre: 'Huevos', cantidad: 4, unidad: 'units', categoria: 'protein' },
        { nombre: 'Diente de ajo', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Aceite de oliva virgen extra', cantidad: 2, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Sal', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Pimienta', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Limpiar los champiñones con un paño y cortarlos en láminas.',
        'Añadir el aceite a una sartén y sofreír el ajo picado a fuego medio.',
        'Añadir los champiñones y cocinar hasta que suelten el agua y se evapore (5-7 min).',
        'Batir los huevos con sal y pimienta en un bol.',
        'Bajar el fuego y añadir los huevos a la sartén. Remover suavemente sin parar.',
        'Retirar cuando aún esté un poco jugoso. Servir inmediatamente.',
      ],
      tiempoMinutos: 15,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['dinner', 'lunch'],
      etiquetas: ['quick', 'high-protein', 'vegetarian', 'gluten-free'],
      notas: 'Opcional: perejil fresco y un chorrito de nata o leche para hacerlo más cremoso.',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-ensalada-manzana-queso-azul',
      source: 'user',
      nombre: 'Ensalada de manzana y queso azul',
      descripcion: 'Ensalada con manzana Granny Smith, queso azul, nueces y vinagreta de mostaza.',
      ingredientes: [
        { nombre: 'Manzana Granny Smith', cantidad: 2, unidad: 'units', categoria: 'fruits' },
        { nombre: 'Queso azul (Roquefort o similar)', cantidad: 100, unidad: 'g', categoria: 'dairy' },
        { nombre: 'Nueces', cantidad: 1, unidad: 'handful', categoria: 'other' },
        { nombre: 'Lechuga iceberg', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Miel', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Aceite de oliva virgen extra', cantidad: 3, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Vinagre', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Mostaza', cantidad: 1, unidad: 'tsp', categoria: 'pantry' },
        { nombre: 'Sal', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Pimienta', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Lavar las hojas verdes y colocarlas en un bol o plato amplio.',
        'Cortar la manzana en láminas finas o cubos. Añadir gotas de limón para que no se oxide.',
        'Desmenuzar el queso azul con las manos por encima.',
        'Incorporar las nueces (se pueden tostar ligeramente en sartén).',
        'Hacer la vinagreta mezclando aceite, vinagre, mostaza, sal y pimienta.',
        'Añadir la miel en hilo fino y aliñar con la vinagreta justo antes de servir.',
      ],
      tiempoMinutos: 10,
      raciones: 2,
      batchCooking: false,
      congelable: false,
      categorias: ['lunch', 'dinner'],
      etiquetas: ['quick', 'vegetarian', 'calcium-rich'],
      notas: '',
      favorita: false,
      creadaEn: '2026-03-29',
    },
    {
      id: 'user-tostada-aguacate-huevos',
      source: 'user',
      nombre: 'Tostada de aguacate y huevos revueltos',
      descripcion: 'Desayuno completo y nutritivo con aguacate cremoso y huevos revueltos sobre pan tostado.',
      ingredientes: [
        { nombre: 'Pan de molde o pan rústico', cantidad: 2, unidad: 'units', categoria: 'grains' },
        { nombre: 'Aguacate maduro', cantidad: 1, unidad: 'unit', categoria: 'vegetables' },
        { nombre: 'Huevos', cantidad: 3, unidad: 'units', categoria: 'protein' },
        { nombre: 'Aceite de oliva virgen extra', cantidad: 1, unidad: 'tbsp', categoria: 'pantry' },
        { nombre: 'Sal', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
        { nombre: 'Pimienta', cantidad: 1, unidad: 'pinch', categoria: 'pantry' },
      ],
      pasos: [
        'Tostar el pan en la tostadora o en una sartén con un poco de aceite.',
        'Cortar el aguacate por la mitad, retirar el hueso y machacar la pulpa con un tenedor. Salpimentar.',
        'Batir los huevos en un bol con una pizca de sal.',
        'Calentar un poco de aceite de oliva en una sartén a fuego medio-bajo.',
        'Añadir los huevos batidos y remover suavemente con una espátula sin parar, hasta que cuajen pero queden jugosos.',
        'Untar el aguacate machacado sobre las tostadas.',
        'Colocar los huevos revueltos encima y añadir pimienta al gusto.',
      ],
      tiempoMinutos: 10,
      raciones: 1,
      batchCooking: false,
      congelable: false,
      categorias: ['breakfast'],
      etiquetas: ['quick', 'high-protein', 'filling'],
      notas: 'Opcional: añadir tomates cherry cortados, semillas de sésamo, copos de chile o unas gotas de limón por encima.',
      favorita: false,
      creadaEn: '2026-03-29',
    },
  ]
}
